import '../design_css/globals.css'
import React from 'react';
export const metadata = {
  title: 'PocketCats',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
